// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Transportes_API.Models;

public partial class TransportesContext : DbContext
{
    public TransportesContext(DbContextOptions<TransportesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Camiones> Camiones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Modern_Spanish_CI_AS");

        modelBuilder.Entity<Camiones>(entity =>
        {
            entity.HasKey(e => e.ID_Camion).HasName("PK__Camiones__91093EF058EFD0FE");

            entity.ToTable(tb => tb.HasTrigger("TR_Bitacorav2"));
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}